services:
  mysql:
    image: mysql:5.6
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_test
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-p$$MYSQL_ROOT_PASSWORD"
        ]
      timeout: 10s
      retries: 10

  test:
    build:
      context: .
      args:
        WC_VERSION: 8.2.2
        WP_VERSION: 6.4.1
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./src:/app/woocommerce/src
      - /app/woocommerce/src/vendor # do not mount vendor inside container
    environment:
      WP_TEST_DATABASE_NAME: wordpress_test
      WP_TEST_DATABASE_USER: root
      WP_TEST_DATABASE_PASSWORD: root
      WP_TEST_DATABASE_HOST: mysql
