services:
  mysql:
    image: mysql:lts
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_test
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      timeout: 2s
      retries: 30

  test:
    build:
      context: ./
      dockerfile: test.Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        WC_VERSION: ${WC_VERSION}
        WP_VERSION: ${WP_VERSION}
    user: ${UID:-1000}:${GID:-1000}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/home/phpuser
      - /home/phpuser/vendor # do not mount vendor inside container
    environment:
      WP_TEST_DATABASE_NAME: wordpress_test
      WP_TEST_DATABASE_USER: root
      WP_TEST_DATABASE_PASSWORD: root
      WP_TEST_DATABASE_HOST: mysql
    entrypoint: ./bin/entrypoint.sh
