"project_id" : "17"
"api_token_env" : "CROWDIN_ALMA_TOKEN"
"base_path" : "src/"
"base_url" : "https://almapay.crowdin.com"
"preserve_hierarchy": true

files:
  -
    source: /languages/alma-woocommerce-gateway.pot
    translation: /languages/alma-woocommerce-gateway-%locale_with_underscore%.po
