version: 3

env:
  PHP_VERSION: '{{ .PHP_VERSION | default "7.4" }}'
  WC_VERSION: '{{ .WC_VERSION | default "8.2.2" }}'
  WP_VERSION: '{{ .WP_VERSION | default "6.4.1" }}'

tasks:
  build:
    desc: Build test container
    cmds:
      - docker compose build

  test:
    desc: Run tests
    deps:
      - build
    cmds:
      - docker compose run --rm test
      - docker compose down --remove-orphans
