<?php

/**
 * @see https://developer.wordpress.org/plugins/settings/options-api/
 */

namespace Alma\Gateway\WooCommerce\Proxy;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class OptionsProxy to manage WordPress/WooCommerce options.
 */
class OptionsProxy {

	/**
	 * Generated by WooCommerce in WC_Settings_API::get_option_key().
	 */
	const OPTIONS_KEY = 'wc_alma_settings';

	public static function get_environment() {
		return get_option( self::OPTIONS_KEY . '_environment', 'test' );
	}
}
