<?php

/**
 * @see https://developer.wordpress.org/plugins/settings/options-api/
 */

namespace Alma\Gateway\WooCommerce\Proxy;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class OptionsProxy to manage WordPress/WooCommerce options.
 */
class OptionsProxy {

	/**
	 * Generated by WooCommerce in WC_Settings_API::get_option_key().
	 */
	const OPTIONS_KEY = 'woocommerce_alma_config_gateway_settings';

	public function get_options(): array {
		$options = get_option( self::OPTIONS_KEY ) ?? array();

		return is_array( $options ) ? $options : array();
	}

	/**
	 * Update a specific option value.
	 *
	 * @param string $option The option name to update.
	 * @param mixed  $value The value to set for the option.
	 *
	 * @return bool
	 */
	public function update_option( string $option, $value ): bool {
		$options            = get_option( self::OPTIONS_KEY ) ?? array();
		$options[ $option ] = $value;

		return update_option( self::OPTIONS_KEY, $options );
	}

	public function delete_option( string $option ): bool {
		$options = get_option( self::OPTIONS_KEY ) ?? array();
		unset( $options[ $option ] );

		return update_option( self::OPTIONS_KEY, $options );
	}
}
