name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: ~

jobs:

  lint:
    name: Lint code
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Lint code
        run: composer phpcs

  test:
    name: Run tests
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      # We are using only the latest supported version as a first step
      matrix:
        include:
          - wc_version: "8.2.2"
            wp_version: "6.4.1"
            php_version: "7.4"

    env:
      PHP_VERSION: ${{ matrix.php_version }}
      WC_VERSION: ${{ matrix.wc_version }}
      WP_VERSION: ${{ matrix.wp_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test container
        uses: docker/bake-action@v5
        with:
          files: compose.yml
          load: true
          targets: test
          set: |
            test.cache-from=type=gha
            test.cache-to=type=gha

      - name: Run tests
        run: docker compose run test

