name: PHP Composer

on:
  push:
    branches: [main,develop]
  pull_request:
    branches: [main,develop]
  workflow_dispatch: ~

jobs:
  lint:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Lint source code
        run: composer phpcs


  test:
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        include:
          - version: "8.1.1"
            wp_version: "6.3.1"
            php_version: "7.4"
          # - version: "3.0.9"
          #   wp_version: "4.7.23"
          #   php_version: "5.6"
          # - version: "4.9.5"
          #   wp_version: 5.3.12"
          #   php_version: "7.0"
          # - version: "5.9.1"
          #   wp_version: "5.6.8"
          #   php_version: "7.2"
          # - version: "6.3.1"
          #   wp_version: "5.9.2"
          #   php_version: "7.2"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
      
      - run: docker run -p 3306:3306  -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -d mysql:latest

      - run: sleep 10

      - run: bash bin/install-wp-tests.sh wordpress_test root '' localhost ${{ matrix.wp_version }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --dev
        working-directory: ./src

      - name: Test source code
        run: bash bin/phpunit
